Repository penumbra-zone/web, pull requests merged in 2024-06, with the labels that each got.

#1041 view: audit action views
  docs/adrs/003-action-views.md
Labels: documentation, privacy

#1249 Properly format if no metadata
  .changeset/shaggy-knives-protect.md
  packages/types/src/value-view.test.ts
  packages/types/src/value-view.ts
Labels: bug

#1140 audit privacy invariants
  docs/adrs/004-privacy-invariants.md
Labels: documentation, security, privacy
